POST http://localhost:8080/api/cards
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "currencyCode": "PLN"
}

###
POST http://localhost:8080/api/cards/5707973928058009/transactions
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "type": "IN",
  "amount": 200,
  "currencyCode": "PLN"
}

###
POST http://localhost:8080/api/cards/5707973928058009/transactions
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "type": "OUT",
  "amount": 100.0,
  "currencyCode": "PLN"
}

###

GET http://localhost:8080/api/cards
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "pageNumber": 0,
  "pageSize": 10
}

###

GET http://localhost:8080/api/cards/5707973928058009
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=
