spring:
  jpa:
    open-in-view: false
    generate-ddl: true
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/payments
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  messages:
    basename: exceptions
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/realms/training
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8100/realms/training
        registration:
          keycloak:
            client-id: training-client
            scope:
              - openid

#  security:
#    user:
#      name: admin
#      password: 123
#      roles: ADMIN
card-number-length: 16
secret: sdfewrtfnmuiretynui
api-keys: 00001,00002