spring:
  datasource:
    url: jdbc:h2:mem:payments
    #url: jdbc:h2:file:./data/payments;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true